FROM python:3.12-bullseye

WORKDIR /app

# Cache dependencies to speed up builds
COPY devops/trino-requirements.txt .
RUN pip install -r trino-requirements.txt

COPY ./src/trino /app/src

# NOTE - This copies shared utilities into the Docker container (e.g., logging)
COPY ./src/common/* /app/src/utilities

WORKDIR /app/src

CMD ["python", "interface.py"]